# Generated by Django 5.2 on 2025-05-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldclock',
            name='uk_time',
            field=models.DateTimeField(),
        ),
    ]
